[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
regex = "1"
petgraph = "0.6"
log = "0.4.27"
